import os
from pathlib import Path
from typing import Dict, Any
from fpdf import FPDF

CONFIG_PATH = Path(__file__).parent / "config.json"

def generate_pdf_report(scan_data: Dict[str, Any], output_path: str) -> str:
    """
    Generates a formal Legal Metrology Compliance Inspection PDF report using fpdf2.
    """
    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Title Header
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(6, 182, 212)  # Cyan accent
    pdf.cell(0, 10, "PramaanCheck - Legal Metrology Compliance Report", ln=True, align="L")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, "Under Legal Metrology (Packaged Commodities) Rules, 2011", ln=True, align="L")
    pdf.line(10, 26, 200, 26)
    pdf.ln(6)

    # Metadata Block
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 6, f"Scan ID: #{scan_data.get('id', 'N/A')}", ln=True)

    pdf.set_font("Helvetica", "", 10)
    pdf.cell(95, 6, f"Image File: {scan_data.get('image_name', 'Unknown')}", ln=False)
    pdf.cell(95, 6, f"Inspector Role: {scan_data.get('user_role', 'inspector').capitalize()}", ln=True)
    pdf.cell(95, 6, f"Scan Timestamp: {scan_data.get('created_at', 'N/A')}", ln=False)
    pdf.cell(95, 6, f"Overall Status: {scan_data.get('overall_status', 'UNKNOWN')}", ln=True)
    pdf.cell(95, 6, f"Compliance Score: {scan_data.get('compliance_score', 0)}%", ln=True)
    pdf.ln(6)

    # Font Check Summary Block
    font_check = scan_data.get("font_check", {})
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "1. Rule 7 Font Height & Width Verification", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 6, font_check.get("rule_7_details", "No font height details recorded."))
    pdf.ln(4)

    # Rule 6 Compliance Checklist Table
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "2. Rule 6 Mandatory Declarations Checklist", ln=True)

    # Table Header
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(60, 7, "Declaration Rule", border=1, fill=True)
    pdf.cell(25, 7, "Section", border=1, fill=True)
    pdf.cell(25, 7, "Status", border=1, fill=True)
    pdf.cell(80, 7, "Inspection Details", border=1, ln=True, fill=True)

    # Table Body
    pdf.set_font("Helvetica", "", 8)
    rule_results = scan_data.get("rule_results", {})
    rules = rule_results.get("rules", [])

    for r in rules:
        status_str = r.get("status", "FAIL")
        # Truncate text if long for clean PDF cells
        rule_name = str(r.get("rule_name", ""))[:32]
        act_sec = str(r.get("act_section", "Rule 6"))[:14]
        details = str(r.get("details", ""))[:55]

        pdf.cell(60, 6, rule_name, border=1)
        pdf.cell(25, 6, act_sec, border=1)
        pdf.cell(25, 6, status_str, border=1)
        pdf.cell(80, 6, details, border=1, ln=True)

    # Footer note
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(120, 120, 120)
    pdf.multi_cell(0, 4, "Note: This report is automatically generated by PramaanCheck. Surface area positioning rules for Principle Display Panel (PDP) are reserved for v2.")

    pdf.output(output_path)
    return output_path
